verbose_commander: false
commander_rate: 40
cruise_height: 2.0
takeoff_height: 2.0
land_height: 0.178

thresh_cruise_height: 0.1
thresh_takeoff_height: 0.05
thresh_land_height: 0.1
thresh_cruise_planar: 0.2

look_ahead: 0.3
enable_prediction: true
co_op: false